//! Build script: generate a compile-time manifest of every Rust source file in
//! `src/`, so the running binary can report its complete file inventory (path +
//! line count) in the debug bundle — a build fingerprint that "incorporates all
//! files". Pure std (no build-dependencies, preserving the no-native-deps Termux
//! build); runs on the HOST during a cross-build, walking the source tree that is
//! present at build time. Output is sorted by path so the generated constant —
//! and therefore the debug bundle — is byte-deterministic.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let mut files: Vec<(String, u32)> = Vec::new();
    collect(Path::new("src"), &mut files);
    files.sort(); // deterministic order (by relative path)

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str(
        "/// Every Rust source file in `src/` at build time: (relative path, line count).\n",
    );
    out.push_str("pub const SOURCE_FILES: &[(&str, u32)] = &[\n");
    let mut total: u32 = 0;
    for (path, lines) in &files {
        let _ = writeln!(out, "    ({path:?}, {lines}),");
        total = total.saturating_add(*lines);
    }
    out.push_str("];\n");
    let _ = writeln!(
        out,
        "/// Total source lines across {} files.\npub const SOURCE_TOTAL_LINES: u32 = {total};",
        files.len()
    );

    let dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    std::fs::write(Path::new(&dir).join("source_manifest.rs"), out)
        .expect("write source_manifest.rs");

    println!("cargo:rerun-if-changed=build.rs");
    // NB: `collect` already emitted a `rerun-if-changed` for every file AND every
    // directory it walked. A directory `rerun-if-changed` only watches its DIRECT
    // children (cargo does not recurse), so a blanket `rerun-if-changed=src` would
    // leave the manifest STALE for every file under src/core, src/modules, … after
    // an edit. Declaring each file (content changes) AND each directory (file
    // add/remove at any depth) is what keeps the manifest accurate.
}

/// Recursively collect `*.rs` files under `dir` as (path-with-forward-slashes,
/// line_count), and declare each visited directory + file as a `rerun-if-changed`
/// input so the manifest is regenerated on any source change at any depth.
fn collect(dir: &Path, out: &mut Vec<(String, u32)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    // Watch this directory so a file added/removed directly under it reruns us.
    println!("cargo:rerun-if-changed={}", dir.display());
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            // Watch this file so a content change reruns us (a directory watch
            // alone does NOT catch edits to files in subdirectories).
            println!("cargo:rerun-if-changed={}", path.display());
            let lines = std::fs::read_to_string(&path).map_or(0, |s| s.lines().count() as u32);
            // Normalise to forward slashes for a stable, readable key.
            let rel = path.to_string_lossy().replace('\\', "/");
            out.push((rel, lines));
        }
    }
}
