//! Build script: generate a compile-time manifest of every Rust source file in
//! `src/`, so the running binary can report its complete file inventory (path +
//! line count) in the debug bundle — a build fingerprint that "incorporates all
//! files". Pure std (no build-dependencies, preserving the no-native-deps Termux
//! build); runs on the HOST during a cross-build, walking the source tree that is
//! present at build time. Output is sorted by path so the generated constant —
//! and therefore the debug bundle — is byte-deterministic.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let mut files: Vec<(String, u32)> = Vec::new();
    collect(Path::new("src"), &mut files);
    files.sort(); // deterministic order (by relative path)

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str(
        "/// Every Rust source file in `src/` at build time: (relative path, line count).\n",
    );
    out.push_str("pub const SOURCE_FILES: &[(&str, u32)] = &[\n");
    let mut total: u32 = 0;
    for (path, lines) in &files {
        let _ = writeln!(out, "    ({path:?}, {lines}),");
        total = total.saturating_add(*lines);
    }
    out.push_str("];\n");
    let _ = writeln!(
        out,
        "/// Total source lines across {} files.\npub const SOURCE_TOTAL_LINES: u32 = {total};",
        files.len()
    );

    let dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    std::fs::write(Path::new(&dir).join("source_manifest.rs"), out)
        .expect("write source_manifest.rs");

    // Rebuild the manifest whenever the source tree changes.
    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=build.rs");
}

/// Recursively collect `*.rs` files under `dir` as (path-with-forward-slashes,
/// line_count). Stable and platform-independent (paths use `/`).
fn collect(dir: &Path, out: &mut Vec<(String, u32)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            let lines = std::fs::read_to_string(&path)
                .map(|s| s.lines().count() as u32)
                .unwrap_or(0);
            // Normalise to forward slashes for a stable, readable key.
            let rel = path.to_string_lossy().replace('\\', "/");
            out.push((rel, lines));
        }
    }
}
