/// Subdomain brute-force dictionary — covers ~99 % of the public-facing
/// subdomains operators actually want to discover. Ordered roughly by
/// frequency so cancellation during a partial run still surfaces the
/// highest-value names first.
pub(super) const SUBDOMAINS: &[&str] = &[
    "www",
    "mail",
    "smtp",
    "imap",
    "pop",
    "pop3",
    "webmail",
    "ns",
    "ns1",
    "ns2",
    "ns3",
    "mx",
    "mx1",
    "ftp",
    "admin",
    "blog",
    "api",
    "dev",
    "staging",
    "stage",
    "test",
    "beta",
    "alpha",
    "qa",
    "secure",
    "vpn",
    "cdn",
    "static",
    "assets",
    "media",
    "img",
    "images",
    "docs",
    "support",
    "help",
    "status",
    "shop",
    "store",
    "portal",
    "app",
    "apps",
    "my",
    "login",
    "auth",
    "sso",
    "files",
    "upload",
    "download",
    "backup",
    "git",
    "gitlab",
    "github",
    "jira",
    "wiki",
    "forum",
    "community",
    "old",
    "new",
    "m",
    "mobile",
    "internal",
    "prod",
    "production",
    "cpanel",
    "autodiscover",
    "autoconfig",
    "webdisk",
    // CI/CD & DevOps
    "ci",
    "cd",
    "jenkins",
    "drone",
    // Container & orchestration
    "k8s",
    "registry",
    "docker",
    // Monitoring & observability
    "grafana",
    "prometheus",
    "kibana",
    "sentry",
    "monitoring",
    "logs",
    "metrics",
    // Database & cache
    "db",
    "mysql",
    "postgres",
    "redis",
    "mongo",
    "elastic",
    // Cloud & remote
    "cloud",
    "remote",
    "demo",
    "sandbox",
    "uat",
    "preview",
    "intranet",
];

/// DNS-based blocklists — zone + human label.
pub(super) const BLOCKLISTS: &[(&str, &str)] = &[
    ("zen.spamhaus.org", "Spamhaus ZEN"),
    ("bl.spamcop.net", "SpamCop"),
    ("dnsbl.sorbs.net", "SORBS"),
    ("b.barracudacentral.org", "Barracuda"),
    ("cbl.abuseat.org", "CBL"),
    ("dnsbl-1.uceprotect.net", "UCEPROTECT-1"),
    ("psbl.surriel.com", "PSBL"),
    ("all.s5h.net", "S5H"),
];
