//! Behaviour of `xtask issue-fix report`. A fake `gh` on the PATH records the arguments and the body
//! it is given, so the test checks what the real command would be asked to post, without a network.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

/// A directory that is removed when the test ends.
struct Scratch(PathBuf);

impl Scratch {
    fn new(name: &str) -> Self {
        let dir = std::env::temp_dir().join(format!("report-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).expect("the scratch directory can be made");
        Self(dir)
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

/// Writes a `gh` that records its arguments in ARGS and its standard input in BODY, then exits with
/// FAKE_GH_STATUS. The directory holding it is put first on the PATH of the run.
fn fake_gh(dir: &Path) -> PathBuf {
    let bin = dir.join("bin");
    fs::create_dir_all(&bin).expect("the fake bin directory can be made");
    let gh = bin.join("gh");
    fs::write(
        &gh,
        "#!/bin/sh\nprintf '%s\\n' \"$*\" > \"$ARGS\"\ncat > \"$BODY\"\nexit \"${FAKE_GH_STATUS:-0}\"\n",
    )
    .expect("the fake gh can be written");
    fs::set_permissions(&gh, fs::Permissions::from_mode(0o755)).expect("the fake gh is executable");
    bin
}

struct Run {
    output: Output,
    args: String,
    body: String,
}

/// Runs `xtask issue-fix report` with the given arguments and environment, against a fake gh.
fn run_report(dir: &Path, args: &[&str], env: &[(&str, &str)], gh_status: &str) -> Run {
    let bin = fake_gh(dir);
    let args_file = dir.join("args.txt");
    let body_file = dir.join("body.md");
    let path = format!(
        "{}:{}",
        bin.display(),
        std::env::var("PATH").unwrap_or_default()
    );
    let mut command = Command::new(env!("CARGO_BIN_EXE_xtask"));
    command
        .args(["issue-fix", "report"])
        .args(args)
        .env("PATH", path)
        .env("ARGS", &args_file)
        .env("BODY", &body_file)
        .env("FAKE_GH_STATUS", gh_status)
        .env_remove("REPO")
        .env_remove("FIX_OUTCOME")
        .env_remove("GATE_OUTCOME")
        .env_remove("PUBLISH_OUTCOME");
    for (name, value) in env {
        command.env(name, value);
    }
    let output = command.output().expect("xtask must run");
    Run {
        output,
        args: fs::read_to_string(&args_file).unwrap_or_default(),
        body: fs::read_to_string(&body_file).unwrap_or_default(),
    }
}

#[test]
fn the_report_posts_the_stage_outcomes_and_the_gate_tail_on_standard_input() {
    let scratch = Scratch::new("posts");
    let log = scratch.path().join("gate.log");
    fs::write(&log, "first\nthe last `line`\n").expect("the gate log can be written");
    let log_arg = log.display().to_string();
    let run = run_report(
        scratch.path(),
        &["42", &log_arg],
        &[
            ("REPO", "fixture/fixture"),
            ("FIX_OUTCOME", "success"),
            ("GATE_OUTCOME", "failure"),
            ("PUBLISH_OUTCOME", "skipped"),
        ],
        "0",
    );
    assert!(
        run.output.status.success(),
        "{}",
        String::from_utf8_lossy(&run.output.stderr)
    );
    assert_eq!(
        run.args.trim_end(),
        "issue comment 42 --repo fixture/fixture --body-file -"
    );
    assert!(run.body.contains(
        "Stage outcomes: fix (model, path policy, capture)=success, repair gate=failure, publish=skipped.\n\n"
    ));
    assert!(
        run.body
            .contains("Last 40 lines of the repair gate:\n\n```\nfirst\nthe last 'line'\n```\n\n")
    );
    assert!(
        run.body
            .ends_with("---\n_Generated by the issue-fix workflow_\n")
    );
}

#[test]
fn an_unset_outcome_reads_as_unknown_and_a_missing_log_has_no_section() {
    let scratch = Scratch::new("unknown");
    let missing = scratch.path().join("absent.log");
    let missing_arg = missing.display().to_string();
    let run = run_report(
        scratch.path(),
        &["7", &missing_arg],
        &[("REPO", "fixture/fixture")],
        "0",
    );
    assert!(run.output.status.success());
    assert!(run.body.contains(
        "fix (model, path policy, capture)=unknown, repair gate=unknown, publish=unknown."
    ));
    assert!(!run.body.contains("Last 40 lines"));
}

#[test]
fn a_report_without_a_repository_is_refused() {
    let scratch = Scratch::new("no-repo");
    let run = run_report(scratch.path(), &["42"], &[], "0");
    assert_eq!(run.output.status.code(), Some(1));
    assert!(String::from_utf8_lossy(&run.output.stderr).contains("REPO must be set"));
    assert!(
        run.args.is_empty(),
        "gh must not be called without a repository"
    );
}

#[test]
fn a_report_without_an_issue_number_is_a_usage_error() {
    let scratch = Scratch::new("no-number");
    let run = run_report(scratch.path(), &[], &[("REPO", "fixture/fixture")], "0");
    assert_eq!(run.output.status.code(), Some(64));
}

#[test]
fn a_failed_comment_is_a_failure() {
    let scratch = Scratch::new("gh-fails");
    let run = run_report(scratch.path(), &["42"], &[("REPO", "fixture/fixture")], "3");
    assert_eq!(run.output.status.code(), Some(1));
}
