pub(super) const GEO_SERVICES: &[(&str, &str, &str)] = &[
    // Australia
    ("commbank.com.au", "Australia", "AU"),
    ("westpac.com.au", "Australia", "AU"),
    ("anz.com.au", "Australia", "AU"),
    ("nab.com.au", "Australia", "AU"),
    ("realestate.com.au", "Australia", "AU"),
    ("domain.com.au", "Australia", "AU"),
    ("seek.com.au", "Australia", "AU"),
    ("gumtree.com.au", "Australia", "AU"),
    ("afterpay.com", "Australia", "AU"),
    ("zip.co", "Australia", "AU"),
    ("bunnings.com.au", "Australia", "AU"),
    ("woolworths.com.au", "Australia", "AU"),
    ("coles.com.au", "Australia", "AU"),
    ("telstra.com.au", "Australia", "AU"),
    ("optus.com.au", "Australia", "AU"),
    ("centrelink.gov.au", "Australia", "AU"),
    ("myob.com", "Australia", "AU"),
    ("xero.com", "New Zealand", "NZ"),
    // United Kingdom
    ("hsbc.co.uk", "United Kingdom", "GB"),
    ("barclays.co.uk", "United Kingdom", "GB"),
    ("lloydsbank.co.uk", "United Kingdom", "GB"),
    ("natwest.com", "United Kingdom", "GB"),
    ("rightmove.co.uk", "United Kingdom", "GB"),
    ("autotrader.co.uk", "United Kingdom", "GB"),
    ("nhs.uk", "United Kingdom", "GB"),
    ("gov.uk", "United Kingdom", "GB"),
    // United States
    ("chase.com", "United States", "US"),
    ("bankofamerica.com", "United States", "US"),
    ("wellsfargo.com", "United States", "US"),
    ("capitalone.com", "United States", "US"),
    ("zillow.com", "United States", "US"),
    ("realtor.com", "United States", "US"),
    ("craigslist.org", "United States", "US"),
    ("usps.com", "United States", "US"),
    ("irs.gov", "United States", "US"),
    ("dmv.org", "United States", "US"),
    // Germany
    ("sparkasse.de", "Germany", "DE"),
    ("commerzbank.de", "Germany", "DE"),
    ("postbank.de", "Germany", "DE"),
    ("immobilienscout24.de", "Germany", "DE"),
    ("mobile.de", "Germany", "DE"),
    // France
    ("labanquepostale.fr", "France", "FR"),
    ("leboncoin.fr", "France", "FR"),
    ("impots.gouv.fr", "France", "FR"),
    // Canada
    ("td.com", "Canada", "CA"),
    ("rbc.com", "Canada", "CA"),
    ("scotiabank.com", "Canada", "CA"),
    ("kijiji.ca", "Canada", "CA"),
    // Japan
    ("rakuten.co.jp", "Japan", "JP"),
    ("yahoo.co.jp", "Japan", "JP"),
    ("mercari.com", "Japan", "JP"),
    // Brazil
    ("mercadolivre.com.br", "Brazil", "BR"),
    ("itau.com.br", "Brazil", "BR"),
    ("bradesco.com.br", "Brazil", "BR"),
    // India
    ("flipkart.com", "India", "IN"),
    ("paytm.com", "India", "IN"),
    ("hdfc.com", "India", "IN"),
    ("icicibank.com", "India", "IN"),
];

pub(super) const CCTLD_MAP: &[(&str, &str, &str)] = &[
    (".com.au", "Australia", "AU"),
    (".net.au", "Australia", "AU"),
    (".org.au", "Australia", "AU"),
    (".gov.au", "Australia", "AU"),
    (".edu.au", "Australia", "AU"),
    (".co.uk", "United Kingdom", "GB"),
    (".org.uk", "United Kingdom", "GB"),
    (".ac.uk", "United Kingdom", "GB"),
    (".gov.uk", "United Kingdom", "GB"),
    (".co.nz", "New Zealand", "NZ"),
    (".co.za", "South Africa", "ZA"),
    (".com.br", "Brazil", "BR"),
    (".co.jp", "Japan", "JP"),
    (".co.kr", "South Korea", "KR"),
    (".co.in", "India", "IN"),
    (".com.sg", "Singapore", "SG"),
    (".com.my", "Malaysia", "MY"),
    (".co.id", "Indonesia", "ID"),
    (".com.ph", "Philippines", "PH"),
    (".com.tw", "Taiwan", "TW"),
    (".com.hk", "Hong Kong", "HK"),
    (".com.mx", "Mexico", "MX"),
    (".com.ar", "Argentina", "AR"),
    (".com.co", "Colombia", "CO"),
    (".com.pe", "Peru", "PE"),
    (".com.ng", "Nigeria", "NG"),
    (".com.eg", "Egypt", "EG"),
    (".com.pk", "Pakistan", "PK"),
    (".com.bd", "Bangladesh", "BD"),
    (".com.vn", "Vietnam", "VN"),
    (".com.tr", "Turkey", "TR"),
    (".com.ua", "Ukraine", "UA"),
    // Simple ccTLDs (lower confidence — many are used internationally)
    (".de", "Germany", "DE"),
    (".fr", "France", "FR"),
    (".it", "Italy", "IT"),
    (".es", "Spain", "ES"),
    (".pt", "Portugal", "PT"),
    (".nl", "Netherlands", "NL"),
    (".be", "Belgium", "BE"),
    (".at", "Austria", "AT"),
    (".ch", "Switzerland", "CH"),
    (".se", "Sweden", "SE"),
    (".no", "Norway", "NO"),
    (".dk", "Denmark", "DK"),
    (".fi", "Finland", "FI"),
    (".pl", "Poland", "PL"),
    (".cz", "Czech Republic", "CZ"),
    (".hu", "Hungary", "HU"),
    (".ro", "Romania", "RO"),
    (".bg", "Bulgaria", "BG"),
    (".hr", "Croatia", "HR"),
    (".sk", "Slovakia", "SK"),
    (".ie", "Ireland", "IE"),
    (".ru", "Russia", "RU"),
    (".jp", "Japan", "JP"),
    (".kr", "South Korea", "KR"),
    (".cn", "China", "CN"),
    (".in", "India", "IN"),
    (".za", "South Africa", "ZA"),
    (".ca", "Canada", "CA"),
    (".mx", "Mexico", "MX"),
    (".br", "Brazil", "BR"),
    (".ar", "Argentina", "AR"),
    (".cl", "Chile", "CL"),
];
