#!/usr/bin/env bash
# shellcheck disable=SC2016 # printf formats carry literal Markdown backticks
# publish.sh OUT_DIR
#
# The publish stage. It runs in a job that holds the write token, from a checkout of
# main and from a copy of the scripts made before anything from the plan stage ran.
# It reads what the plan stage wrote to OUT_DIR. The patch is data: it is applied to
# main, checked against the path policy, and only then committed.
#
# A green plan pushes dual-pass/issue-N and opens a pull request. A plan that needs a
# human pushes dual-pass/issue-N-wip when it has a change, labels the issue, and
# comments with the reason. Neither path merges anything.
#
# Environment: REPO and ISSUE_NUMBER. GH_TOKEN carries the push, labels, comments, and
# pull requests. POLICY names the path-policy script, a copy of the issue-fix one.
# REMOTE_URL pushes to that URL instead of origin, and DRY_RUN=1 skips every gh call;
# the offline self-check uses both.
set -euo pipefail

out="${1:?usage: publish.sh OUT_DIR}"
number="${ISSUE_NUMBER:?ISSUE_NUMBER must be set}"
policy="${POLICY:?POLICY must name the path-policy script}"
if [[ ! "$number" =~ ^[0-9]+$ ]]; then
  echo "publish: issue number is not numeric: $number" >&2
  exit 1
fi
remote="${REMOTE_URL:-origin}"
outcome="$(cat "$out/outcome")"

# Runs git against the remote. The token travels in an extra header, so neither the
# URL nor the checkout's configuration keeps it.
remote_git() {
  if [[ -n "${REMOTE_URL:-}" ]]; then
    git "$@"
  else
    local auth
    auth="$(printf 'x-access-token:%s' "${GH_TOKEN:?GH_TOKEN must be set}" | base64 | tr -d '\n')"
    git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic ${auth}" "$@"
  fi
}

# Runs gh, or announces the call and skips it in a dry run.
run_gh() {
  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    echo "publish: dry run, skipped: gh $*"
    return 0
  fi
  gh "$@"
}

# Pushes BRANCH. When the remote already has it, the push is leased to the tip seen
# now, so a push that lands in between is refused. The branch is the bot's own, and a
# re-run replaces it.
push_branch() {
  local branch="$1" tip=""
  tip="$(remote_git ls-remote --heads "$remote" "refs/heads/$branch" | awk 'NR == 1 { print $1 }')" || true
  local lease=()
  if [[ -n "$tip" ]]; then
    lease=("--force-with-lease=refs/heads/$branch:$tip")
  fi
  remote_git push -q ${lease[@]+"${lease[@]}"} "$remote" "HEAD:refs/heads/$branch"
}

case "$outcome" in
  green) branch="dual-pass/issue-$number" ;;
  needs-human-review) branch="dual-pass/issue-$number-wip" ;;
  *) echo "publish: unknown outcome: $outcome" >&2; exit 1 ;;
esac

has_change=0
if [[ -s "$out/change.patch" ]]; then
  has_change=1
fi
if [[ "$outcome" == "green" && "$has_change" -ne 1 ]]; then
  echo "publish: a green plan produced no change" >&2
  exit 1
fi

if [[ "$has_change" -eq 1 ]]; then
  git checkout -q -B "$branch"
  if ! git apply --index "$out/change.patch"; then
    echo "publish: the patch does not apply to $(git rev-parse --short HEAD)" >&2
    exit 1
  fi
  # The policy governs the change. It runs before the record of the change is added.
  bash "$policy" HEAD
  if [[ -f "$out/execution-plan.json" ]]; then
    cp "$out/execution-plan.json" execution-plan.json
  fi
  cp "$out/dual-pass-report.md" dual-pass-report.md
  git add -- execution-plan.json dual-pass-report.md
  git -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
    -c user.name="github-actions[bot]" \
    commit -q -m "dual-pass: issue $number ($outcome)"
  push_branch "$branch"
fi

if [[ "$outcome" == "green" ]]; then
  existing=""
  if [[ "${DRY_RUN:-0}" != "1" ]]; then
    existing="$(gh pr list --repo "${REPO:?REPO must be set}" --head "$branch" --state open \
      --json number --jq '.[0].number // empty')"
  fi
  if [[ -n "$existing" ]]; then
    echo "publish: pull request #$existing is already open for $branch"
  else
    run_gh pr create --repo "$REPO" --base main --head "$branch" \
      --title "dual-pass: issue $number" --body-file "$out/dual-pass-report.md"
  fi
  echo "publish: green, branch $branch"
  exit 0
fi

# needs-human-review: label the issue and say why. The reason and the tail of the
# report are the record; nothing from the model is involved here.
body="$(mktemp)"
{
  printf 'Dual-pass needs a human before it can open a pull request.\n\n'
  printf '%s\n\n' "$(cat "$out/reason.md" 2>/dev/null || echo 'no reason was recorded')"
  printf '```\n%s\n```\n\n' "$(tail -n 80 "$out/dual-pass-report.md" 2>/dev/null || true)"
  printf -- '---\n_Generated by the dual-pass workflow_\n'
} > "$body"
run_gh label create needs-human-review --repo "${REPO:?REPO must be set}" --color B60205 \
  --description "Dual-pass budget exhausted" >/dev/null 2>&1 || true
run_gh issue edit "$number" --repo "$REPO" --add-label needs-human-review
run_gh issue comment "$number" --repo "$REPO" --body-file "$body"
echo "publish: needs-human-review, wip branch $([[ "$has_change" -eq 1 ]] && echo "$branch" || echo none)"
