#!/usr/bin/env bash
# shellcheck disable=SC2016 # printf formats carry literal Markdown backticks
# publish.sh OUT_DIR
#
# The publish stage. It runs in a job that holds the write token, from a checkout of
# main and from a copy of the scripts made before anything from the plan stage ran.
# It reads what the plan stage wrote to OUT_DIR. The patch is data: it is applied to
# main, checked against the path policy, and only then committed.
#
# A green plan pushes dual-pass/issue-N and opens a pull request. A plan that needs a
# human pushes dual-pass/issue-N-wip when it has a change, labels the issue, and
# comments with the reason. Neither path merges anything. A change that cannot be
# published, because the patch does not apply, the policy refuses it, or the push fails,
# still labels the issue and comments the reason, and then publish exits 1.
#
# Environment: REPO and ISSUE_NUMBER. GH_TOKEN carries the push, labels, comments, and
# pull requests. POLICY names the path-policy script, a copy of the issue-fix one.
# REMOTE_URL pushes to that URL instead of origin, and DRY_RUN=1 skips every gh call;
# the offline self-check uses both.
set -euo pipefail

out="${1:?usage: publish.sh OUT_DIR}"
number="${ISSUE_NUMBER:?ISSUE_NUMBER must be set}"
policy="${POLICY:?POLICY must name the path-policy script}"
repo="${REPO:?REPO must be set}"
if [[ ! "$number" =~ ^[0-9]+$ ]]; then
  echo "publish: issue number is not numeric: $number" >&2
  exit 1
fi
remote="${REMOTE_URL:-origin}"

# Runs git against the remote. The token travels in an extra header, so neither the
# URL nor the checkout's configuration keeps it.
remote_git() {
  if [[ -n "${REMOTE_URL:-}" ]]; then
    git "$@"
  else
    local auth
    auth="$(printf 'x-access-token:%s' "${GH_TOKEN:?GH_TOKEN must be set}" | base64 | tr -d '\n')"
    git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic ${auth}" "$@"
  fi
}

# Runs gh, or announces the call and skips it in a dry run.
run_gh() {
  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    echo "publish: dry run, skipped: gh $*"
    return 0
  fi
  gh "$@"
}

# Pushes BRANCH. When the remote already has it, the push is leased to the tip seen
# now, so a push that lands in between is refused. The branch is the bot's own, and a
# re-run replaces it. Returns non-zero when the remote cannot be read or refuses the push.
push_branch() {
  local branch="$1" listing="" tip=""
  if ! listing="$(remote_git ls-remote --heads "$remote" "refs/heads/$branch")"; then
    return 1
  fi
  tip="$(awk 'NR == 1 { print $1 }' <<< "$listing")"
  local lease=()
  if [[ -n "$tip" ]]; then
    lease=("--force-with-lease=refs/heads/$branch:$tip")
  fi
  remote_git push -q ${lease[@]+"${lease[@]}"} "$remote" "HEAD:refs/heads/$branch"
}

# Labels the issue and comments the plan's reason, the publish failure when there is one,
# and the tail of the report. Both calls are made even when the first fails, so the
# comment is posted either way. Returns non-zero when either call failed.
hand_off() {
  local note="$1" status=0 body=""
  if ! body="$(mktemp)"; then
    return 1
  fi
  {
    printf 'Dual-pass needs a human before it can open a pull request.\n\n'
    printf '%s\n\n' "$(cat "$out/reason.md" 2>/dev/null || echo 'no reason was recorded')"
    if [[ -n "$note" ]]; then
      printf 'Publish stopped: %s\n\n' "$note"
    fi
    printf '```\n%s\n```\n\n' "$(tail -n 80 "$out/dual-pass-report.md" 2>/dev/null || true)"
    printf -- '---\n_Generated by the dual-pass workflow_\n'
  } > "$body"
  run_gh label create needs-human-review --repo "$repo" --color B60205 \
    --description "Dual-pass needs a human" >/dev/null 2>&1 || true
  if ! run_gh issue edit "$number" --repo "$repo" --add-label needs-human-review; then
    echo "publish: could not add the needs-human-review label to #$number" >&2
    status=1
  fi
  if ! run_gh issue comment "$number" --repo "$repo" --body-file "$body"; then
    echo "publish: could not comment on #$number" >&2
    status=1
  fi
  rm -f "$body"
  return "$status"
}

# Says why a change was not published, hands the issue to a person, and exits 1.
give_up() {
  echo "publish: $1" >&2
  if ! hand_off "$1"; then
    echo "publish: the hand-off to a person did not finish on #$number" >&2
  fi
  exit 1
}

outcome=""
if ! outcome="$(cat "$out/outcome" 2>/dev/null)"; then
  give_up "no outcome was recorded in $out"
fi

case "$outcome" in
  green) branch="dual-pass/issue-$number" ;;
  needs-human-review) branch="dual-pass/issue-$number-wip" ;;
  *) give_up "unknown outcome: $outcome" ;;
esac

has_change=0
if [[ -s "$out/change.patch" ]]; then
  has_change=1
fi
if [[ "$outcome" == "green" && "$has_change" -ne 1 ]]; then
  give_up "a green plan produced no change"
fi

if [[ "$has_change" -eq 1 ]]; then
  if ! git checkout -q -B "$branch"; then
    give_up "could not check out a branch for $branch"
  fi
  if ! git apply --index "$out/change.patch"; then
    give_up "the patch does not apply to main"
  fi
  # The policy governs the change. It runs before the record of the change is added.
  if ! bash "$policy" HEAD; then
    give_up "the path policy refused the change"
  fi
  record=(dual-pass-report.md)
  if [[ -f "$out/execution-plan.json" ]]; then
    if ! cp "$out/execution-plan.json" execution-plan.json; then
      give_up "could not copy the plan into the checkout"
    fi
    record=(execution-plan.json "${record[@]}")
  fi
  if ! cp "$out/dual-pass-report.md" dual-pass-report.md; then
    give_up "could not copy the report into the checkout"
  fi
  if ! git add -- "${record[@]}"; then
    give_up "could not stage the record of the change"
  fi
  if ! git -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
    -c user.name="github-actions[bot]" \
    commit -q -m "dual-pass: issue $number ($outcome)"; then
    give_up "could not commit the change"
  fi
  if ! push_branch "$branch"; then
    give_up "could not push $branch"
  fi
fi

if [[ "$outcome" == "green" ]]; then
  existing=""
  if [[ "${DRY_RUN:-0}" != "1" ]]; then
    if ! existing="$(gh pr list --repo "$repo" --head "$branch" --state open \
      --json number --jq '.[0].number // empty')"; then
      give_up "could not list the open pull requests for $branch"
    fi
  fi
  if [[ -n "$existing" ]]; then
    echo "publish: pull request #$existing is already open for $branch"
  elif ! run_gh pr create --repo "$repo" --base main --head "$branch" \
    --title "dual-pass: issue $number" --body-file "$out/dual-pass-report.md"; then
    give_up "could not open a pull request for $branch"
  fi
  echo "publish: green, branch $branch"
  exit 0
fi

# needs-human-review: label the issue and say why. The reason and the tail of the report
# are the record; nothing from the model is involved here.
if ! hand_off ""; then
  echo "publish: the needs-human-review label or comment did not post on #$number" >&2
  exit 1
fi
if [[ "$has_change" -eq 1 ]]; then
  echo "publish: needs-human-review, wip branch $branch"
else
  echo "publish: needs-human-review, no branch pushed"
fi
