#!/usr/bin/env bash
# publish.sh ISSUE_JSON AGENT_JSON
#
# Commits the change on ai-fix/issue-N, pushes that branch, and opens a pull
# request against main. It never merges.
#
# Environment: REPO (owner/name). PUSH_TOKEN and GH_TOKEN for the push and for gh.
# HAS_PAT is "true" when PUSH_TOKEN is a personal or app token rather than the
# workflow token; the pull request body says so when it is not.
# DRY_RUN=1 pushes to REMOTE_URL and skips gh, so the offline self-check can run it.
set -euo pipefail

issue_json="${1:?usage: publish.sh ISSUE_JSON AGENT_JSON}"
agent_json="${2:?usage: publish.sh ISSUE_JSON AGENT_JSON}"
repo="${REPO:?REPO must be set}"

number=$(jq -r '.number' "$issue_json")
title=$(jq -r '.title' "$issue_json")
branch="ai-fix/issue-$number"

if [[ -z "$(git status --porcelain)" ]]; then
  echo "publish: the agent left no changes" >&2
  exit 1
fi

git checkout -q -b "$branch"
git add -A
git -c user.name="issue-fix" -c user.email="issue-fix@users.noreply.github.com" \
  commit -q -m "Fix #$number: $title" \
  -m "Refs #$number. Produced by the issue-fix workflow. It passed the path policy and the full repair gate. It needs review before merge."

remote="${REMOTE_URL:-https://x-access-token:${PUSH_TOKEN:?PUSH_TOKEN must be set}@github.com/${repo}.git}"
git remote set-url origin "$remote"
git push -q -u origin "$branch"

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  echo "publish: dry run pushed $branch and skipped the pull request"
  exit 0
fi

summary=$(jq -r '.result // "(no summary returned)"' "$agent_json")
body_file="$(mktemp)"
{
  printf 'Closes #%s\n\n' "$number"
  printf '## Model summary (unreviewed)\n\n%s\n\n' "$summary"
  printf '## What the workflow checked\n\n'
  printf -- '- Path policy: changes only under src/, plus new files under tests/.\n'
  # The backticks are literal Markdown, not command substitution.
  # shellcheck disable=SC2016
  printf -- '- `scripts/repair-gate.sh full` passed on the runner.\n\n'
  if [[ "${HAS_PAT:-false}" != "true" ]]; then
    printf 'This pull request was opened with the workflow token. GitHub does not start CI for pull requests opened that way, so start CI from the Actions tab or set the ISSUE_FIX_TOKEN secret.\n\n'
  fi
  printf 'Needs human review. This pull request does not merge automatically.\n\n'
  printf -- '---\n_Generated by the issue-fix workflow with Claude Code_\n'
} > "$body_file"

gh pr create --repo "$repo" --base main --head "$branch" \
  --title "Fix #$number: $title" --body-file "$body_file"
