#!/usr/bin/env bash
# publish.sh ISSUE_JSON CHANGE_DIR
#
# Applies the agent's patch to a checkout of main, checks the result against the path
# policy, commits it on ai-fix/issue-N, pushes that branch, and opens a pull request
# against main. It never merges.
#
# Run it from a checkout that the agent never touched, using a copy of the scripts made
# before the patch arrived. The patch is data. Nothing from the patch is executed here,
# and the policy checks what the patch does to main.
#
# The gate tested the commit GATED_SHA. The change is published only while main is still
# that commit, so a pull request is never a combination the gate did not run on.
#
# Environment: REPO and GATED_SHA. PUSH_TOKEN and GH_TOKEN carry the push and gh.
# HAS_PAT is "true" when PUSH_TOKEN is a personal or app token, not the workflow token.
# REMOTE_URL pushes to that URL instead of origin, and DRY_RUN=1 skips gh; the offline
# self-check uses both.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
issue_json="${1:?usage: publish.sh ISSUE_JSON CHANGE_DIR}"
change_dir="${2:?usage: publish.sh ISSUE_JSON CHANGE_DIR}"
repo="${REPO:?REPO must be set}"
gated="${GATED_SHA:?GATED_SHA must name the commit the gate tested}"
patch="$change_dir/change.patch"
agent_json="$change_dir/agent.json"

number=$(jq -r '.number' "$issue_json")
title=$(jq -r '.title' "$issue_json")
if [[ ! "$number" =~ ^[0-9]+$ ]]; then
  echo "publish: issue number is not numeric: $number" >&2
  exit 1
fi
branch="ai-fix/issue-$number"
remote="${REMOTE_URL:-origin}"

# Runs git against the remote. The token travels in an extra header, so neither the
# URL nor the checkout's configuration keeps it.
remote_git() {
  if [[ -n "${REMOTE_URL:-}" ]]; then
    git "$@"
  else
    local auth
    auth="$(printf 'x-access-token:%s' "${PUSH_TOKEN:?PUSH_TOKEN must be set}" | base64 | tr -d '\n')"
    git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic ${auth}" "$@"
  fi
}

if [[ ! -s "$patch" ]]; then
  echo "publish: there is no patch at $patch" >&2
  exit 1
fi

# The gate tested GATED_SHA. Publishing from any other main would ship a change the gate
# did not see, so main must still be that commit.
main_sha="$(git rev-parse HEAD)"
if [[ "$main_sha" != "$gated" ]]; then
  echo "publish: main is $main_sha, but the gate tested $gated; main moved while the run was in progress, so label the issue again" >&2
  exit 1
fi

# An existing branch is never overwritten. The maintainer decides what to do with it.
set +e
remote_git ls-remote --exit-code --heads "$remote" "$branch" >/dev/null 2>&1
status=$?
set -e
case "$status" in
  0)
    echo "publish: $branch already exists on the remote; delete or rename it, then label the issue again" >&2
    exit 1
    ;;
  2) ;;
  *)
    echo "publish: could not read the remote heads (exit $status)" >&2
    exit 1
    ;;
esac

git checkout -q -b "$branch"
if ! git apply --index "$patch"; then
  echo "publish: the patch does not apply to $(git rev-parse --short HEAD)" >&2
  exit 1
fi
staged=0
git diff --cached --quiet --no-ext-diff || staged=$?
case "$staged" in
  0)
    echo "publish: the patch changes nothing" >&2
    exit 1
    ;;
  1) ;;
  *)
    echo "publish: git diff failed (exit $staged)" >&2
    exit 1
    ;;
esac
bash "$here/check-protected.sh" HEAD

git -c user.name="issue-fix" -c user.email="issue-fix@users.noreply.github.com" \
  commit -q -m "Fix #$number: $title" \
  -m "Refs #$number. Produced by the issue-fix workflow. It passed the path policy and the full repair gate. It needs review before merge."

remote_git push -q "$remote" "$branch"

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  echo "publish: dry run pushed $branch and skipped the pull request"
  exit 0
fi

summary=$(jq -r '((.result // "(no summary returned)") | tostring)[0:4000]' "$agent_json")
body_file="$(mktemp)"
{
  printf 'Closes #%s\n\n' "$number"
  printf '## Model summary (unreviewed)\n\n%s\n\n' "$summary"
  printf '## What the workflow checked\n\n'
  printf -- '- Built on main at %s, the commit the gate tested.\n' "$main_sha"
  printf -- '- Path policy, applied to the patch on main: changes only under src/, outside the test code, plus new files under src/ and tests/.\n'
  # The backticks are literal Markdown, not command substitution.
  # shellcheck disable=SC2016
  printf -- '- `cargo run --locked -p xtask -- gate full` passed on the runner.\n\n'
  if [[ "${HAS_PAT:-false}" != "true" ]]; then
    printf 'This pull request was opened with the workflow token. GitHub does not start CI for pull requests opened that way, so start CI from the Actions tab or set the ISSUE_FIX_TOKEN secret.\n\n'
  fi
  printf 'Needs human review. This pull request does not merge automatically.\n\n'
  printf -- '---\n_Generated by the issue-fix workflow with Claude Code_\n'
} > "$body_file"

gh pr create --repo "$repo" --base main --head "$branch" \
  --title "Fix #$number: $title" --body-file "$body_file"
