#!/usr/bin/env bash
# report.sh ISSUE_NUMBER [GATE_LOG]
#
# Comments on the issue when an attempt stops before a pull request exists. It
# reports each stage's outcome and the tail of the repair gate log. The gate runs the
# tests the model wrote, so that log can contain text the model chose. The tail is
# therefore posted only as a code block, with backticks removed and each line cut to
# 400 characters, and the model's own summary is never posted here.
#
# Environment: REPO, GH_TOKEN, and the job outcomes FIX_OUTCOME (the model, the path
# policy, and the capture), GATE_OUTCOME (the repair gate), and PUBLISH_OUTCOME.
set -euo pipefail

number="${1:?usage: report.sh ISSUE_NUMBER [GATE_LOG]}"
gate_log="${2:-/dev/null}"
repo="${REPO:?REPO must be set}"
body="$(mktemp)"

{
  printf 'The issue-fix attempt stopped before it opened a pull request.\n\n'
  printf 'Stage outcomes: fix (model, path policy, capture)=%s, repair gate=%s, publish=%s.\n\n' \
    "${FIX_OUTCOME:-unknown}" "${GATE_OUTCOME:-unknown}" "${PUBLISH_OUTCOME:-unknown}"
  if [[ -s "$gate_log" ]]; then
    printf 'Last 40 lines of the repair gate:\n\n```\n'
    tail -n 40 "$gate_log" | tr '`' "'" | cut -c1-400
    printf '```\n\n'
  fi
  printf 'Nothing was merged. A maintainer can fix the issue by hand, or label it again once the cause is addressed.\n\n'
  printf -- '---\n_Generated by the issue-fix workflow_\n'
} > "$body"

gh issue comment "$number" --repo "$repo" --body-file "$body"
