#!/usr/bin/env bash
# report.sh ISSUE_NUMBER [GATE_LOG]
#
# Comments on the issue when an attempt stops before a pull request exists. It
# reports each stage's outcome and the tail of the repair gate log, which holds
# compiler and test output only. It never includes model output.
#
# Environment: REPO, GH_TOKEN, and the stage outcomes AGENT_OUTCOME, GUARD_OUTCOME,
# GATE_OUTCOME, PUBLISH_OUTCOME.
set -euo pipefail

number="${1:?usage: report.sh ISSUE_NUMBER [GATE_LOG]}"
gate_log="${2:-/dev/null}"
repo="${REPO:?REPO must be set}"
body="$(mktemp)"

{
  printf 'The issue-fix attempt stopped before it opened a pull request.\n\n'
  printf 'Stage outcomes: agent=%s, path policy=%s, repair gate=%s, publish=%s.\n\n' \
    "${AGENT_OUTCOME:-unknown}" "${GUARD_OUTCOME:-unknown}" \
    "${GATE_OUTCOME:-unknown}" "${PUBLISH_OUTCOME:-unknown}"
  if [[ -s "$gate_log" ]]; then
    printf 'Last 40 lines of the repair gate:\n\n```\n'
    tail -n 40 "$gate_log" | tr '`' "'"
    printf '```\n\n'
  fi
  printf 'Nothing was merged. A maintainer can fix the issue by hand, or label it again once the cause is addressed.\n\n'
  printf -- '---\n_Generated by the issue-fix workflow_\n'
} > "$body"

gh issue comment "$number" --repo "$repo" --body-file "$body"
