//! The report posted when an attempt stops before a pull request exists. It states each stage's
//! outcome and the tail of the repair gate log. The gate runs the tests the model wrote, so the log
//! can hold text that the model chose. The tail is therefore posted only as a code block, with
//! backticks replaced and each line cut to 400 bytes. The model's own summary is never posted here.

use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::{Command, ExitCode, Stdio};

use crate::error::{self, Error, Result};

const USAGE: &str = "usage: xtask issue-fix report ISSUE_NUMBER [GATE_LOG]";
const GATE_TAIL_LINES: usize = 40;
const GATE_LINE_BYTES: usize = 400;

/// `issue-fix report ISSUE_NUMBER [GATE_LOG]`: comments on the issue with the stage outcomes and the
/// gate log tail. The outcomes come from FIX_OUTCOME, GATE_OUTCOME, and PUBLISH_OUTCOME, and REPO names
/// the repository. The comment is posted with gh, which reads GH_TOKEN from the environment.
pub fn run(args: &[String]) -> ExitCode {
    let (number, gate_log) = match args {
        [number] => (number, None),
        [number, log] => (number, Some(Path::new(log))),
        _ => return error::usage(USAGE),
    };
    if number.is_empty() {
        return error::usage(USAGE);
    }
    match report(number, gate_log) {
        Ok(()) => ExitCode::SUCCESS,
        Err(problem) => error::report("report", &problem),
    }
}

fn report(number: &str, gate_log: Option<&Path>) -> Result<()> {
    let repo = match std::env::var("REPO") {
        Ok(repo) if !repo.is_empty() => repo,
        _ => return Err(Error::Refused("REPO must be set".to_owned())),
    };
    let gate_tail = match gate_log {
        Some(path) if has_content(path) => Some(gate_tail(&read_log(path)?)),
        _ => None,
    };
    let body = render(
        &stage("FIX_OUTCOME"),
        &stage("GATE_OUTCOME"),
        &stage("PUBLISH_OUTCOME"),
        gate_tail.as_deref(),
    );
    post_comment(number, &repo, &body)
}

/// An outcome from the environment. An unset or empty value reads as "unknown".
fn stage(name: &str) -> String {
    match std::env::var(name) {
        Ok(value) if !value.is_empty() => value,
        _ => "unknown".to_owned(),
    }
}

/// Whether the log exists and holds bytes. This is the `-s` test the original used, which is false
/// for a missing file and for an empty one.
fn has_content(path: &Path) -> bool {
    fs::metadata(path).is_ok_and(|meta| meta.len() > 0)
}

fn read_log(path: &Path) -> Result<Vec<u8>> {
    fs::read(path).map_err(|source| Error::Io {
        path: path.to_path_buf(),
        source,
    })
}

/// The report body. The stage line and the closing lines are fixed text. The gate section appears
/// only when there is a tail to show.
fn render(fix: &str, gate: &str, publish: &str, gate_tail: Option<&[u8]>) -> Vec<u8> {
    let mut body = Vec::new();
    body.extend_from_slice(b"The issue-fix attempt stopped before it opened a pull request.\n\n");
    body.extend_from_slice(
        format!(
            "Stage outcomes: fix (model, path policy, capture)={fix}, repair gate={gate}, publish={publish}.\n\n"
        )
        .as_bytes(),
    );
    if let Some(tail) = gate_tail {
        body.extend_from_slice(b"Last 40 lines of the repair gate:\n\n```\n");
        body.extend_from_slice(tail);
        body.extend_from_slice(b"```\n\n");
    }
    body.extend_from_slice(
        b"Nothing was merged. A maintainer can fix the issue by hand, or label it again once the cause is addressed.\n\n",
    );
    body.extend_from_slice(b"---\n_Generated by the issue-fix workflow_\n");
    body
}

/// The last GATE_TAIL_LINES lines of LOG. Backticks become single quotes, and each line is cut to
/// GATE_LINE_BYTES bytes, which is what `tail | tr | cut -c1-400` produced. Each line ends with a
/// newline, so a log that lacks a final newline still ends its last line, as cut wrote it.
fn gate_tail(log: &[u8]) -> Vec<u8> {
    let mut lines: Vec<&[u8]> = log.split(|&byte| byte == b'\n').collect();
    if log.ends_with(b"\n") {
        lines.pop();
    }
    let start = lines.len().saturating_sub(GATE_TAIL_LINES);
    let mut out = Vec::new();
    for line in lines.get(start..).unwrap_or_default() {
        out.extend(
            line.iter()
                .take(GATE_LINE_BYTES)
                .map(|&byte| if byte == b'`' { b'\'' } else { byte }),
        );
        out.push(b'\n');
    }
    out
}

/// Posts BODY as a comment on issue NUMBER through gh, with the body read from standard input.
/// gh's own output, the comment's address, passes through to this step's output.
fn post_comment(number: &str, repo: &str, body: &[u8]) -> Result<()> {
    let args = [
        "issue",
        "comment",
        number,
        "--repo",
        repo,
        "--body-file",
        "-",
    ];
    let shown = format!("gh {}", args.join(" "));
    let mut child = Command::new("gh")
        .args(args)
        .stdin(Stdio::piped())
        .spawn()
        .map_err(|source| Error::Command {
            shown: shown.clone(),
            reason: format!("could not start: {source}"),
        })?;
    if let Some(mut stdin) = child.stdin.take() {
        stdin.write_all(body).map_err(|source| Error::Command {
            shown: shown.clone(),
            reason: format!("could not send the body: {source}"),
        })?;
    }
    let status = child.wait().map_err(|source| Error::Command {
        shown: shown.clone(),
        reason: format!("could not be waited for: {source}"),
    })?;
    if status.success() {
        Ok(())
    } else {
        Err(Error::Command {
            shown,
            reason: format!("exited with {status}"),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_unset_outcome_reads_as_unknown_in_the_stage_line() {
        let body = render("unknown", "unknown", "unknown", None);
        let text = String::from_utf8(body).expect("utf-8 body");
        assert!(text.contains(
            "Stage outcomes: fix (model, path policy, capture)=unknown, repair gate=unknown, publish=unknown.\n\n"
        ));
        assert!(!text.contains("Last 40 lines"));
    }

    #[test]
    fn the_gate_section_is_a_code_block_with_the_tail() {
        let text = render("failure", "failure", "skipped", Some(b"one\n"));
        let text = String::from_utf8(text).expect("utf-8 body");
        assert!(text.contains("Last 40 lines of the repair gate:\n\n```\none\n```\n\n"));
    }

    #[test]
    fn the_tail_keeps_the_last_forty_lines() {
        let log: String = (1..=50).map(|n| format!("line {n}\n")).collect();
        let tail = gate_tail(log.as_bytes());
        let text = String::from_utf8(tail).expect("utf-8 tail");
        assert_eq!(text.lines().count(), 40);
        assert!(text.starts_with("line 11\n"));
        assert!(text.ends_with("line 50\n"));
    }

    #[test]
    fn backticks_become_quotes_and_lines_are_cut_to_400_bytes() {
        let mut long = "`".repeat(300);
        long.push_str(&"x".repeat(200));
        let tail = gate_tail(format!("{long}\n").as_bytes());
        assert_eq!(tail.len(), 401);
        assert_eq!(tail.first(), Some(&b'\''));
        assert_eq!(tail.last(), Some(&b'\n'));
    }

    #[test]
    fn a_log_without_a_final_newline_still_ends_its_last_line() {
        assert_eq!(gate_tail(b"a\nb"), b"a\nb\n");
        assert_eq!(gate_tail(b"a\n"), b"a\n");
        assert_eq!(gate_tail(b"\n"), b"\n");
    }

    #[test]
    fn an_empty_or_missing_log_has_no_section() {
        assert!(!has_content(Path::new("/nonexistent/gate.log")));
        assert!(!has_content(Path::new("/dev/null")));
    }
}
