//! API-domain → service-tag lookup for stealer/breach record routing.
//!
//! Extracted from `key_harvest::mod.rs` so the lookup table doesn't
//! dominate the file. Used by `store_api_credential` to tag a record
//! when the URL field carries a known provider domain.

pub(super) const API_SERVICE_DOMAINS: &[(&str, &str)] = &[
    // ── Self-discovery: finding more OathNet keys scales our own quota ──
    ("oathnet.org", "oathnet"),
    ("oathnet.com", "oathnet"),
    ("api.oathnet.org", "oathnet"),
    ("dashboard.oathnet.org", "oathnet"),
    ("docs.oathnet.org", "oathnet"),
    // ── OathNet competitors (same data, parallel quota pools) ───────────
    ("see-know.eu", "see_know"),
    ("api.see-know.eu", "see_know"),
    ("app.see-know.eu", "see_know"),
    ("dashboard.see-know.eu", "see_know"),
    ("snusbase.com", "snusbase"),
    ("api.snusbase.com", "snusbase"),
    ("leakcheck.io", "leakcheck"),
    ("leakcheck.net", "leakcheck"),
    ("api.leakcheck.net", "leakcheck"),
    ("leakpeek.com", "leakpeek"),
    ("leak-lookup.com", "leak_lookup"),
    ("api.leak-lookup.com", "leak_lookup"),
    ("hashes.com", "hashes"),
    ("psbdmp.ws", "psbdmp"),
    ("ghostproject.fr", "ghostproject"),
    ("scylla.so", "scylla"),
    ("scylla.sh", "scylla"),
    ("weleakinfo.to", "weleakinfo"),
    ("weleakinfo.com", "weleakinfo"),
    ("hackcheck.io", "hackcheck"),
    ("api.hackcheck.io", "hackcheck"),
    ("scrubd.com", "scrubd"),
    ("nuclearleaks.com", "nuclearleaks"),
    ("breachforums.is", "breachforums"),
    ("breachforums.st", "breachforums"),
    ("inteltechniques.com", "inteltechniques"),
    // ── Existing entries ────────────────────────────────────────────────
    ("shodan.io", "shodan"),
    ("account.shodan.io", "shodan"),
    ("virustotal.com", "virustotal"),
    ("hunter.io", "hunter"),
    ("securitytrails.com", "securitytrails"),
    ("dehashed.com", "dehashed"),
    ("app.dehashed.com", "dehashed"),
    ("api.dehashed.com", "dehashed"),
    ("intelx.io", "intelx"),
    ("2.intelx.io", "intelx"),
    ("free.intelx.io", "intelx"),
    ("numverify.com", "numverify"),
    ("wigle.net", "wigle"),
    ("ipqualityscore.com", "ipqs"),
    ("leakix.net", "leakix"),
    ("haveibeenpwned.com", "hibp"),
    ("censys.io", "censys"),
    ("search.censys.io", "censys"),
    ("binaryedge.io", "binaryedge"),
    ("app.binaryedge.io", "binaryedge"),
    ("greynoise.io", "greynoise"),
    ("viz.greynoise.io", "greynoise"),
    ("fullhunt.io", "fullhunt"),
    ("urlscan.io", "urlscan"),
    ("abuseipdb.com", "abuseipdb"),
    ("serpapi.com", "serpapi"),
    ("criminalip.io", "criminal_ip"),
    ("api.criminalip.io", "criminal_ip"),
    ("abuse.ch", "threatfox"),
    ("openai.com", "openai"),
    ("api.openai.com", "openai"),
    ("anthropic.com", "anthropic"),
    ("api.anthropic.com", "anthropic"),
    ("passivetotal.org", "passivetotal"),
    ("riskiq.net", "passivetotal"),
    ("onyphe.io", "onyphe"),
    ("zoomeye.org", "zoomeye"),
    ("api.zoomeye.org", "zoomeye"),
    ("fofa.info", "fofa"),
    ("en.fofa.info", "fofa"),
    ("netlas.io", "netlas"),
    ("app.netlas.io", "netlas"),
    ("pulsedive.com", "pulsedive"),
    ("builtwith.com", "builtwith"),
    ("emailrep.io", "emailrep"),
    ("seon.io", "seon"),
    ("api.seon.io", "seon"),
    ("epieos.com", "epieos"),
    ("api.epieos.com", "epieos"),
    ("nubela.co", "proxycurl"),
    ("opencorporates.com", "opencorporates"),
    ("api.opencorporates.com", "opencorporates"),
    ("whoisxmlapi.com", "whoisxml"),
    ("breachdirectory.org", "breachdirectory"),
    ("c99.nl", "c99"),
    ("api.c99.nl", "c99"),
    ("twilio.com", "twilio"),
    ("console.twilio.com", "twilio"),
    ("app.snyk.io", "snyk"),
    ("snyk.io", "snyk"),
    ("cloud.digitalocean.com", "digitalocean"),
    ("digitalocean.com", "digitalocean"),
    ("ngrok.com", "ngrok"),
    ("dashboard.ngrok.com", "ngrok"),
    ("mailchimp.com", "mailchimp"),
    ("app.mailchimp.com", "mailchimp"),
    ("discord.com", "discord"),
    ("discordapp.com", "discord"),
    ("registry.npmjs.org", "npm"),
    ("pypi.org", "pypi"),
    ("vercel.com", "vercel"),
    ("app.netlify.com", "netlify"),
    ("heroku.com", "heroku"),
    ("dashboard.heroku.com", "heroku"),
    // AI / ML platforms
    ("openrouter.ai", "openrouter"),
    ("console.groq.com", "groq"),
    ("groq.com", "groq"),
    ("cohere.ai", "cohere"),
    ("dashboard.cohere.ai", "cohere"),
    ("mistral.ai", "mistral"),
    ("console.mistral.ai", "mistral"),
    ("together.ai", "together_ai"),
    ("api.together.xyz", "together_ai"),
    ("fal.ai", "fal_ai"),
    ("wandb.ai", "wandb"),
    ("app.wandb.ai", "wandb"),
    ("huggingface.co", "huggingface"),
    ("replicate.com", "replicate"),
    ("lightning.ai", "lightning_ai"),
    ("perplexity.ai", "perplexity"),
    // Cloud / hosting
    ("railway.app", "railway"),
    ("render.com", "render"),
    ("dashboard.render.com", "render"),
    ("supabase.com", "supabase"),
    ("app.supabase.com", "supabase"),
    ("clerk.com", "clerk"),
    ("dashboard.clerk.com", "clerk"),
    ("posthog.com", "posthog"),
    ("app.posthog.com", "posthog"),
    ("flagsmith.com", "flagsmith"),
    ("resend.com", "resend"),
    // Security / OSINT
    ("greynoise.io", "greynoise"),
    ("viz.greynoise.io", "greynoise"),
    ("gitlab.com", "gitlab"),
    ("riskiq.net", "riskiq"),
    ("community.riskiq.com", "riskiq"),
    ("spyse.com", "spyse"),
    ("securitytrails.com", "securitytrails"),
    ("app.securitytrails.com", "securitytrails"),
    // Mapping
    ("mapbox.com", "mapbox"),
    ("account.mapbox.com", "mapbox"),
    ("geocodio.io", "geocodio"),
    // Payment
    ("paystack.com", "paystack"),
    ("dashboard.paystack.com", "paystack"),
    ("razorpay.com", "razorpay"),
    ("dashboard.razorpay.com", "razorpay"),
    // Communication
    ("postmarkapp.com", "postmark"),
    ("account.postmarkapp.com", "postmark"),
    ("mailersend.com", "mailersend"),
    ("app.mailersend.com", "mailersend"),
    // Database
    ("cloud.mongodb.com", "mongodb_atlas"),
    ("atlas.mongodb.com", "mongodb_atlas"),
    ("neon.tech", "neon"),
    ("console.neon.tech", "neon"),
    ("planetscale.com", "planetscale"),
    ("app.planetscale.com", "planetscale"),
    ("upstash.com", "upstash"),
    ("console.upstash.com", "upstash"),
    // OSINT / validation (complete coverage)
    ("opencellid.org", "opencellid"),
    ("unwiredlabs.com", "opencellid"),
];

pub(super) fn identify_service_from_url(url: &str) -> &'static str {
    let lower = url.to_lowercase();
    for (domain, service) in API_SERVICE_DOMAINS {
        if lower.contains(domain) {
            return service;
        }
    }
    "unknown"
}
