//! Reconstructed huntsman.
//! Recorder contract, identity, GEOINT, hashed ledger, STIX and Navigator gates, plus a
//! guarded HTTP layer (`egress`, `http`, `fetch`, `keys`, `deadline`). Challenge pages are not results.
//! Pure logic stays separate from I/O so every decision can be tested without a network.

#![deny(unsafe_code)]
#![cfg_attr(test, allow(unknown_lints, clippy::assert_is_empty))]
#![allow(
    clippy::items_after_statements,
    clippy::missing_errors_doc,
    clippy::missing_panics_doc
)]

pub mod address_au;
pub mod analysis;
pub mod archive;
pub mod archive_bridge;
pub mod artifacts;
pub mod asic_director;
pub mod asic_persons;
pub mod assurance;
pub mod atproto;
pub mod attack;
pub mod attack_catalog;
pub mod attack_types;
pub mod au_electoral;
pub mod au_id;
pub mod au_people;
pub mod benchmark;
pub mod bluesky_user;
pub mod breach;
pub mod canonical;
pub mod circuit;
pub mod ckan;
pub mod claim_coverage;
pub mod claim_policy;
pub mod classifier;
pub mod classify;
pub mod classify_module;
pub mod collection;
pub mod collector;
pub mod community;
pub mod confidence;
pub mod coref;
pub mod correlation_bridge;
pub mod correlator;
pub mod coverage;
pub mod credential_origin;
pub mod cross_scan;
pub mod crtsh;
pub mod deadline;
pub mod dependency;
pub mod diamond;
pub mod diff;
pub mod differential;
pub mod dmarc;
pub mod dns;
pub mod domain_lifecycle;
pub mod domains;
pub mod egress;
pub mod email_cli;
pub mod email_save;
pub mod engineering_command;
pub mod entity;
pub mod error;
pub mod eval;
pub mod event;
pub mod evidence_ancestry;
pub mod exposure;
pub mod fetch;
pub mod fetch_cli;
pub mod fsio;
pub mod gap;
pub mod geo;
pub mod geohash;
pub mod geoint;
pub mod geometry;
pub mod gexf;
pub mod github_user;
pub mod graph;
pub mod gravatar;
pub mod hibp;
pub mod http;
pub mod identity;
pub mod identity_resolution;
pub mod intelligence;
pub mod json;
pub mod key_health;
pub mod keys;
pub mod leads;
pub mod ledger;
pub mod lineage;
pub mod lookup_save;
pub mod md5;
pub mod mediawiki;
pub mod metrics;
pub mod module;
pub mod navigator;
pub mod oui;
pub mod oui_ieee;
pub mod path;
pub mod people_cli;
pub mod people_save;
pub mod phone_cli;
pub mod phone_intl;
pub mod phone_save;
pub mod pipeline;
pub mod pipeline_limits;
pub mod pivot;
pub mod place;
pub mod planner;
pub mod postcode_au;
pub mod profiles;
pub mod proof;
pub mod radar;
pub mod recon;
pub mod redact;
pub mod relation;
pub mod resolve;
pub mod retrieval_artifact;
pub mod rf;
pub mod roi;
pub mod runtime;
pub mod scan_batch;
pub mod scraper_health;
pub mod search;
pub mod seeknow;
pub mod seeknow_cli;
pub mod seeknow_collector;
pub mod service_defs;
pub mod session;
pub mod sf_compat;
pub mod sha256;
pub mod shadow_assessment;
pub mod signals;
pub mod snake_graph;
pub mod source_outcome;
pub mod source_registry;
pub mod spf;
pub mod stage;
pub mod stix;
pub mod stolen_tax;
pub mod store;
pub mod tags;
pub mod termination;
pub mod textnorm;
pub mod timefmt;
pub mod timeline;
pub mod tlsrpt;
pub mod trust;
pub mod uid;
pub mod union_find;
pub mod username_cli;
pub mod username_save;
pub mod username_variants;
pub mod validation;
pub mod value_syntax;
pub mod wayback;
pub mod web_query;
pub mod web_server;
pub mod xml;

pub use entity::{Entity, EntityKind, EntityRef, Evidence, EvidenceProvenance};
pub use error::Error;
pub use graph::{EntityRelation, RelationKind};
pub use ledger::{
    Claim, LedgerEntry, admitted, append, chain_intact, load_chain, save_chain, seal,
};
pub use session::Session;
pub use stage::{EvidenceLevel, Status};
