//! Huntsman Search Engine (HSE) — an all-source OSINT / GEOINT / NETINT
//! reconnaissance engine in the GhostSec tradition: SpiderFoot-inspired breadth
//! without the daemon or the footprint.
//!
//! Pure-Rust and keyless-first, forged to run entirely inside Termux on aarch64
//! Android with no root. Boots either as a CLI (`hse scan|live|modules|doctor`)
//! or as `hse serve` — an axum HTTP server with a minimal hand-rolled SPA bound
//! to `127.0.0.1` for use from Chrome / Firefox on the device.
//!
//! Architecture invariants (do not change):
//!   - `#![forbid(unsafe_code)]`
//!   - No native-TLS or C-linked deps (rustls + bundled-sqlite only)
//!   - GREATEST-semantics entity merge
//!   - SHA-256 deterministic entity UIDs
//!   - Runtime AI-independence: NO AI / ML / LLM / cloud-inference / agent /
//!     vector-DB / embedding dependency is compiled in. Every runtime capability
//!     is deterministic, documented Rust, so findings reproduce identically on
//!     Termux aarch64 (no root), Linux, and CI with no AI or network-inference
//!     available. AI is a development-time accelerator only. Enforced by the
//!     `runtime_carries_no_ai_ml_inference_dependency` guard in
//!     `tests/architecture.rs`, which is the authoritative statement of the
//!     rule and carries the full rationale.

#![forbid(unsafe_code)]
// HSE is an *application* crate: its library is read by the maintainer with
// `cargo doc --document-private-items`, not consumed as a published API. Doc
// comments on public items therefore link to private helpers (`build_entities`,
// per-module mappers, …) deliberately, because those links resolve and are
// useful when browsing the whole tree. We keep the high-value
// `broken_intra_doc_links` lint denied in CI (it catches typo'd/renamed
// references — real rot) and relax only this stylistic, library-oriented one.
#![allow(rustdoc::private_intra_doc_links)]

pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Compile-time inventory of every Rust source file in `src/` — generated by
/// `build.rs` (sorted, deterministic). Lets the debug bundle report the complete
/// file manifest the binary was built from (`SOURCE_FILES`, `SOURCE_TOTAL_LINES`)
/// — a build fingerprint that accounts for every file, not just runtime modules.
pub mod source_manifest {
    include!(concat!(env!("OUT_DIR"), "/source_manifest.rs"));
}

/// Default bind address for the HTTP server. Localhost only — no LAN exposure.
pub const DEFAULT_BIND: &str = "127.0.0.1:8080";

/// Per-module timeout in milliseconds (architecture invariant).
pub const MODULE_TIMEOUT_MS: u64 = 3000;

/// Tokio worker thread count (architecture invariant — tuned for Termux).
pub const WORKER_THREADS: usize = 2;

/// Upper bound on tokio's blocking-thread pool (`spawn_blocking` + `tokio::fs`).
/// Tokio defaults to **512**, which on a low-RAM Termux/aarch64 phone lets a
/// burst of synchronous sqlite / filesystem work spawn hundreds of OS threads —
/// each with its own stack. HSE is network/IO-bound on a 2-worker runtime, so a
/// small pool is ample; this bounds peak memory without serialising any
/// realistic workload. Applied in `main` via a hand-built runtime.
pub const MAX_BLOCKING_THREADS: usize = 16;

/// Default seconds between `hse live` iterations (the `--interval` default and
/// the API's live-request fallback). The only live-mode tuning constant that is
/// actually wired: `--depth`/`--throttle` default to 0 (seed-only, un-throttled)
/// per iteration by design, and there is no concurrency knob — the former
/// `LIVE_MAX_DEPTH`/`LIVE_DEFAULT_THROTTLE_MS`/`LIVE_DEFAULT_CONCURRENT` were
/// aspirational values that never matched a real default and never had a reader.
pub const LIVE_DEFAULT_INTERVAL_SECS: u64 = 30;

pub mod api;
pub mod app;
pub mod audit;
pub mod cli;
pub mod core;
pub mod modules;
pub mod selftest;
pub mod storage;
pub mod util;

/// True if we appear to be running inside Termux on Android.
pub fn is_termux() -> bool {
    std::env::var_os("TERMUX_VERSION").is_some()
        || std::path::Path::new("/data/data/com.termux").exists()
}

/// Resolve the default database path, creating the parent directory if needed.
///
/// Termux: `$HOME/.huntsman/huntsman.db` (typically under `/data/data/com.termux/files/home`).
/// Falls back to `./.huntsman/huntsman.db` if `$HOME` is unset (see
/// [`crate::util::paths::huntsman_dir`] — the layout stays together under
/// `.huntsman` rather than scattering a bare file into the CWD).
pub fn default_db_path() -> String {
    // `~/.huntsman` created 0700 (owner-only) by `paths::data_file` so the store +
    // dossiers + key pool under it aren't world-listable (PROBLEM_TREE §7 S3).
    crate::util::paths::data_file("huntsman.db")
        .to_string_lossy()
        .into_owned()
}

#[cfg(test)]
mod tests {
    include!("lib_tests.rs");
}
