use super::*;

    #[test]
    fn version_is_non_empty() {
        assert!(!VERSION.is_empty());
    }

    #[test]
    fn source_manifest_is_complete_sorted_and_consistent() {
        use crate::source_manifest::{SOURCE_FILES, SOURCE_TOTAL_LINES};
        // Non-trivial inventory generated by build.rs.
        assert!(SOURCE_FILES.len() > 100, "expected the full src/ tree");
        // Deterministic order — sorted by path (the debug bundle relies on this).
        assert!(
            SOURCE_FILES.windows(2).all(|w| w[0].0 <= w[1].0),
            "SOURCE_FILES must be sorted by path"
        );
        // The entry points are present, and every path is a `src/…/*.rs`.
        assert!(SOURCE_FILES.iter().any(|(p, _)| *p == "src/lib.rs"));
        assert!(SOURCE_FILES.iter().any(|(p, _)| *p == "src/main.rs"));
        assert!(
            SOURCE_FILES
                .iter()
                .all(|(p, _)| p.starts_with("src/") && p.ends_with(".rs")),
        );
        // The reported total matches the per-file sum.
        let sum: u32 = SOURCE_FILES.iter().map(|(_, n)| n).sum();
        assert_eq!(sum, SOURCE_TOTAL_LINES);
    }

    #[test]
    fn source_manifest_line_counts_match_on_disk() {
        // Guards build.rs `rerun-if-changed` correctness: a manifest entry's line
        // count must equal the file's ACTUAL count. A `rerun-if-changed=src`
        // directory watch only catches DIRECT children (cargo doesn't recurse), so
        // it left subdirectory files stale after edits — this asserts the per-file
        // watch keeps them accurate. Read via the compile-time CARGO_MANIFEST_DIR.
        use crate::source_manifest::SOURCE_FILES;
        let root = env!("CARGO_MANIFEST_DIR");
        for rel in [
            "src/lib.rs",
            "src/main.rs",
            // A nested-subdirectory sample (the point of this test, per the
            // comment above) — was src/core/entity/mod.rs until that module
            // moved to the hse-core crate (shared with a wasm32 web-UI build).
            "src/core/mod.rs",
            "src/modules/mod.rs",
        ] {
            let recorded = SOURCE_FILES
                .iter()
                .find(|(p, _)| *p == rel).map_or_else(|| panic!("{rel} missing from manifest"), |(_, n)| *n);
            let actual = std::fs::read_to_string(format!("{root}/{rel}"))
                .unwrap_or_else(|_| panic!("cannot read {rel}"))
                .lines()
                .count() as u32;
            assert_eq!(
                recorded, actual,
                "manifest LOC for {rel} is stale — build.rs rerun-if-changed gap?"
            );
        }
    }

    #[test]
    fn logic_fingerprint_is_the_hash_of_the_module_logic_on_disk() {
        // REQ-CACHE-002: the inter-scan cache keys on `LOGIC_FINGERPRINT`, so it
        // must be exactly the hash of the logic this binary runs. Re-derived here
        // independently of build.rs, from the spec: FNV-1a 64 over the sorted
        // (path, NUL, u64-LE length, contents) of every file under `src/` and
        // `hse-core/src/` that is neither test material nor the browser UI, plus
        // `Cargo.lock`. A build.rs that hashed test code (every
        // test edit would cool every cache), skipped contents, `hse-core`, the
        // embedded data or the lock file (a fix there would replay stale
        // answers), or depended on `read_dir` order disagrees with this value.
        use std::path::{Path, PathBuf};

        const OFFSET: u64 = 14_695_981_039_346_656_037;
        const PRIME: u64 = 1_099_511_628_211;
        fn fnv1a(mut h: u64, bytes: &[u8]) -> u64 {
            for &b in bytes {
                h = (h ^ u64::from(b)).wrapping_mul(PRIME);
            }
            h
        }
        fn fingerprinted(rel: &str) -> bool {
            let name = rel.rsplit('/').next().unwrap_or(rel);
            let in_test_dir = rel
                .split('/')
                .rev()
                .skip(1)
                .any(|d| matches!(d, "tests" | "testdata"));
            !(in_test_dir
                || rel.starts_with("src/web/")
                || name.starts_with("test_")
                || name == "tests.rs"
                || name.ends_with("_tests.rs"))
        }
        fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
            let entries = std::fs::read_dir(dir)
                .unwrap_or_else(|e| panic!("cannot list {}: {e}", dir.display()));
            for entry in entries {
                let path = entry.expect("directory entry").path();
                if path.is_dir() {
                    walk(root, &path, out);
                    continue;
                }
                let rel = path
                    .strip_prefix(root)
                    .expect("walked path is under the root")
                    .to_string_lossy()
                    .replace('\\', "/");
                if fingerprinted(&rel) {
                    out.push((rel, path));
                }
            }
        }

        // The reference hash is itself pinned to the published FNV-1a 64
        // vectors (draft-eastlake-fnv), so agreement below is agreement with
        // FNV-1a, not with a shared mistake.
        assert_eq!(fnv1a(OFFSET, b""), 0xcbf2_9ce4_8422_2325);
        assert_eq!(fnv1a(OFFSET, b"a"), 0xaf63_dc4c_8601_ec8c);
        assert_eq!(fnv1a(OFFSET, b"foobar"), 0x8594_4171_f739_67e8);

        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let mut files = Vec::new();
        for sub in ["src", "hse-core/src"] {
            walk(root, &root.join(sub), &mut files);
        }
        let lock = root.join("Cargo.lock");
        if lock.is_file() {
            files.push(("Cargo.lock".to_string(), lock));
        }
        files.sort();

        // The walk's premises, so a broken walk cannot pass vacuously.
        let has = |p: &str| files.iter().any(|(rel, _)| rel == p);
        assert!(has("src/core/engine/dispatch.rs"), "module logic is in");
        assert!(has("hse-core/src/lib.rs"), "the entity model is in");
        assert!(
            has("src/util/domains/public_suffix_list.dat") && has("src/util/oui/ieee.bin"),
            "the data modules embed is in"
        );
        assert!(
            !has("src/lib_tests.rs") && !has("src/core/engine/tests.rs"),
            "test code is out"
        );
        assert!(!has("src/core/test_support.rs"), "test support is out");
        assert!(
            !files.iter().any(|(rel, _)| rel.starts_with("src/web/")),
            "the browser UI is out"
        );

        let mut h = OFFSET;
        for (rel, path) in &files {
            let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("cannot read {rel}: {e}"));
            h = fnv1a(h, rel.as_bytes());
            h = fnv1a(h, &[0]);
            h = fnv1a(h, &(bytes.len() as u64).to_le_bytes());
            h = fnv1a(h, &bytes);
        }
        assert_eq!(
            crate::source_manifest::LOGIC_FINGERPRINT,
            format!("{h:016x}"),
            "LOGIC_FINGERPRINT is not the hash of the module logic on disk — \
             build.rs's fingerprint drifted from its spec, or went stale \
             (a rerun-if-changed gap)"
        );
    }

    #[test]
    fn architecture_constants_are_correct() {
        assert_eq!(DEFAULT_BIND, "127.0.0.1:8080");
        assert_eq!(MODULE_TIMEOUT_MS, 3000);
        assert_eq!(WORKER_THREADS, 2);
        assert_eq!(MAX_BLOCKING_THREADS, 16);
        assert_eq!(LIVE_DEFAULT_INTERVAL_SECS, 30);
    }

    #[test]
    fn is_termux_returns_false_in_ci() {
        if std::env::var_os("TERMUX_VERSION").is_none() {
            assert!(!is_termux());
        }
    }

    #[test]
    fn default_db_path_is_non_empty() {
        let p = default_db_path();
        assert!(!p.is_empty());
        assert!(p.ends_with("huntsman.db"));
    }

    #[test]
    fn default_db_path_uses_home_when_set() {
        if std::env::var("HOME").is_ok() {
            let p = default_db_path();
            assert!(p.contains(".huntsman"));
        }
    }
