use super::*;

    #[test]
    fn version_is_non_empty() {
        assert!(!VERSION.is_empty());
    }

    #[test]
    fn source_manifest_is_complete_sorted_and_consistent() {
        use crate::source_manifest::{SOURCE_FILES, SOURCE_TOTAL_LINES};
        // Non-trivial inventory generated by build.rs.
        assert!(SOURCE_FILES.len() > 100, "expected the full src/ tree");
        // Deterministic order — sorted by path (the debug bundle relies on this).
        assert!(
            SOURCE_FILES.windows(2).all(|w| w[0].0 <= w[1].0),
            "SOURCE_FILES must be sorted by path"
        );
        // The entry points are present, and every path is a `src/…/*.rs`.
        assert!(SOURCE_FILES.iter().any(|(p, _)| *p == "src/lib.rs"));
        assert!(SOURCE_FILES.iter().any(|(p, _)| *p == "src/main.rs"));
        assert!(
            SOURCE_FILES
                .iter()
                .all(|(p, _)| p.starts_with("src/") && p.ends_with(".rs")),
        );
        // The reported total matches the per-file sum.
        let sum: u32 = SOURCE_FILES.iter().map(|(_, n)| n).sum();
        assert_eq!(sum, SOURCE_TOTAL_LINES);
    }

    #[test]
    fn source_manifest_line_counts_match_on_disk() {
        // Guards build.rs `rerun-if-changed` correctness: a manifest entry's line
        // count must equal the file's ACTUAL count. A `rerun-if-changed=src`
        // directory watch only catches DIRECT children (cargo doesn't recurse), so
        // it left subdirectory files stale after edits — this asserts the per-file
        // watch keeps them accurate. Read via the compile-time CARGO_MANIFEST_DIR.
        use crate::source_manifest::SOURCE_FILES;
        let root = env!("CARGO_MANIFEST_DIR");
        for rel in [
            "src/lib.rs",
            "src/main.rs",
            "src/core/entity/mod.rs",
            "src/modules/mod.rs",
        ] {
            let recorded = SOURCE_FILES
                .iter()
                .find(|(p, _)| *p == rel)
                .map(|(_, n)| *n)
                .unwrap_or_else(|| panic!("{rel} missing from manifest"));
            let actual = std::fs::read_to_string(format!("{root}/{rel}"))
                .unwrap_or_else(|_| panic!("cannot read {rel}"))
                .lines()
                .count() as u32;
            assert_eq!(
                recorded, actual,
                "manifest LOC for {rel} is stale — build.rs rerun-if-changed gap?"
            );
        }
    }

    #[test]
    fn architecture_constants_are_correct() {
        assert_eq!(DEFAULT_BIND, "127.0.0.1:8080");
        assert_eq!(MODULE_TIMEOUT_MS, 3000);
        assert_eq!(WORKER_THREADS, 2);
        assert_eq!(MAX_BLOCKING_THREADS, 16);
        assert_eq!(LIVE_DEFAULT_INTERVAL_SECS, 30);
        assert_eq!(LIVE_MAX_DEPTH, 5);
        assert_eq!(LIVE_DEFAULT_THROTTLE_MS, 100);
        assert_eq!(LIVE_DEFAULT_CONCURRENT, 4);
    }

    #[test]
    fn is_termux_returns_false_in_ci() {
        if std::env::var_os("TERMUX_VERSION").is_none() {
            assert!(!is_termux());
        }
    }

    #[test]
    fn default_db_path_is_non_empty() {
        let p = default_db_path();
        assert!(!p.is_empty());
        assert!(p.ends_with("huntsman.db"));
    }

    #[test]
    fn default_db_path_uses_home_when_set() {
        if std::env::var("HOME").is_ok() {
            let p = default_db_path();
            assert!(p.contains(".huntsman"));
        }
    }
